`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 29.05.2026 00:57:12
// Design Name: 
// Module Name: router_top
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

module router_top (
    input  logic       clk,             // Master system clock
    input  logic       resetn,          // Active-low global hardware reset
    input  logic [7:0] datain,          // 8-bit parallel incoming packet data bus
    input  logic       pkt_valid,       // Asserted by external sender indicating active stream
    input  logic       read_enb_0,      // Read permit driven by external receiver on Channel 0
    input  logic       read_enb_1,      // Read permit driven by external receiver on Channel 1
    input  logic       read_enb_2,      // Read permit driven by external receiver on Channel 2
    
    output logic [7:0] data_out_0,      // 8-bit output data bus for Channel 0
    output logic [7:0] data_out_1,      // 8-bit output data bus for Channel 1
    output logic [7:0] data_out_2,      // 8-bit output data bus for Channel 2
    output logic       vld_out_0,       // Outbound data validation flag for Channel 0
    output logic       vld_out_1,       // Outbound data validation flag for Channel 1
    output logic       vld_out_2,       // Outbound data validation flag for Channel 2
    output logic       busy,            // Stall command forcing external sender to freeze transmission
    output logic       error            // Parity error detection alert pin
);

    // =============================================================================
    // INTERNAL WIRE AND BUS INTERCONNECIONS (ASIC Structural Netlist Highways)
    // =============================================================================
    
    // Control lines driven by the FSM Brain Unit
    logic       wire_detect_add;
    logic       wire_lfd_state;
    logic       wire_ld_state;
    logic       wire_laf_state;
    logic       wire_full_state;
    logic       wire_write_en_reg;
    logic       wire_rst_int_reg;

    // Control and status lines driven by the Synchronizer Unit
    logic [2:0] wire_write_enb;
    logic       wire_fifo_full;
    logic       wire_soft_reset_0;
    logic       wire_soft_reset_1;
    logic       wire_soft_reset_2;

    // Status signals generated by the Datapath Register Unit
    logic [7:0] wire_d_out;
    logic       wire_low_pkt_valid;
    logic       wire_parity_done;

    // Hardwired status lines coming out of the individual FIFO Blocks
    logic       wire_empty_0;
    logic       wire_empty_1;
    logic       wire_empty_2;
    logic       wire_full_0;
    logic       wire_full_1;
    logic       wire_full_2;


    // =============================================================================
    // MODULE INSTANTIATIONS (Stitching the Core Hardware Blocks together)
    // =============================================================================

    // 1. Instantiation of the Central Finite State Machine (FSM Brain)
    router_fsm FSM_BRAIN_UNIT (
        .clk              (clk),
        .resetn           (resetn),
        .pkt_valid        (pkt_valid),
        .datain           (datain[1:0]),       // Feeds address bits to FSM for initial path routing evaluation
        .fifo_empty0      (wire_empty_0),      // Maps empty line from FIFO 0 to FSM port 'fifo_empty0'
        .fifo_empty1      (wire_empty_1),      // Maps empty line from FIFO 1 to FSM port 'fifo_empty1'
        .fifo_empty2      (wire_empty_2),      // Maps empty line from FIFO 2 to FSM port 'fifo_empty2'
        .fifo_full        (wire_fifo_full),    // Multiplexed active channel full flag from Synchronizer
        .low_pkt_valid    (wire_low_pkt_valid),// Handshake back from Register tracking aborted transfers
        .parity_done      (wire_parity_done),  // Count tracking update signal from Register
        .soft_reset_0     (wire_soft_reset_0), // Watchdog link for Channel 0
        .soft_reset_1     (wire_soft_reset_1), // Watchdog link for Channel 1
        .soft_reset_2     (wire_soft_reset_2), // Watchdog link for Channel 2
        .busy             (busy),              // Drives the chip's external busy pin
        .detect_add       (wire_detect_add),
        .lfd_state        (wire_lfd_state),
        .ld_state         (wire_ld_state),
        .full_state       (wire_full_state),
        .laf_state        (wire_laf_state),
        .write_en_reg     (wire_write_en_reg),
        .rst_int_reg      (wire_rst_int_reg)
    );

    // 2. Instantiation of the Synchronizer (The Master Traffic Controller)
    router_sync #(
        .TIMEOUT_LIMIT    (30)                 // Preserves the 30-cycle parameterized watchdog constraint
    ) SYNCHRONIZER_UNIT (
        .clk              (clk),
        .resetn           (resetn),
        .detect_add       (wire_detect_add),
        .write_enb_reg    (wire_write_en_reg), // Connects the gated write control permit from the FSM
        .read_enb_0       (read_enb_0),
        .read_enb_1       (read_enb_1),
        .read_enb_2       (read_enb_2),
        .empty_0          (wire_empty_0),
        .empty_1          (wire_empty_1),
        .empty_2          (wire_empty_2),
        .full_0           (wire_full_0),
        .full_1           (wire_full_1),
        .full_2           (wire_full_2),
        .datain           (datain[1:0]),       // Connects raw stream address configuration bits
        .vld_out_0        (vld_out_0),         // Directly drives external output valid pin 0
        .vld_out_1        (vld_out_1),         // Directly drives external output valid pin 1
        .vld_out_2        (vld_out_2),         // Directly drives external output valid pin 2
        .write_enb        (wire_write_enb),    // Generates the decoded 3-bit one-hot channel writing array
        .fifo_full        (wire_fifo_full),    // Outputs active multiplexed feedback straight to FSM input
        .soft_reset_0     (wire_soft_reset_0),
        .soft_reset_1     (wire_soft_reset_1),
        .soft_reset_2     (wire_soft_reset_2)
    );

    // 3. Instantiation of the Datapath Router Register (The Math & Staging Engine)
    router_reg DATAPATH_REG_UNIT (
        .clk              (clk),
        .resetn           (resetn),
        .datain           (datain),            // Connects the full 8-bit streaming parallel data bus
        .lfd_state        (wire_lfd_state),
        .ld_state         (wire_ld_state),
        .laf_state        (wire_laf_state),
        .full_state       (wire_full_state),
        .rst_int_reg      (wire_rst_int_reg),
        .d_out            (wire_d_out),        // Outputs stabilized, multiplexed byte bus to all parallel FIFOs
        .low_pkt_valid    (wire_low_pkt_valid),
        .parity_done      (wire_parity_done),
        .error            (error)              // Connects the chip's continuous parity error diagnostic alert pin
    );

    // 4. Instantiation of Storage Queue Channel 0 (FIFO 0)
    router_fifo #(
        .DEPTH            (16),
        .DATA_WIDTH       (8),
        .ADDR_WIDTH       (4)
    ) FIFO_CHANNEL_0 (
        .clk              (clk),
        .resetn           (resetn),
        .soft_reset       (wire_soft_reset_0), // Fed by dedicated Watchdog loop 0 from Synchronizer
        .write_enb        (wire_write_enb[0]), // Activated when wire_write_enb decoded output array = 3'b001
        .read_enb         (read_enb_0),
        .lfd_state        (wire_lfd_state),    // Feeds master pulse to latch internal lfd_state_reg tracking register
        .d_in             (wire_d_out),        // Receives shared internal data pipeline bus
        .d_out            (data_out_0),        // Drives the physical external data output channel 0 pins
        .vld_out          (),                  // Left un-connected because Synchronizer Block 1 handles vld_out logic paths
        .full             (wire_full_0),
        .empty            (wire_empty_0)
    );

    // 5. Instantiation of Storage Queue Channel 1 (FIFO 1)
    router_fifo #(
        .DEPTH            (16),
        .DATA_WIDTH       (8),
        .ADDR_WIDTH       (4)
    ) FIFO_CHANNEL_1 (
        .clk              (clk),
        .resetn           (resetn),
        .soft_reset       (wire_soft_reset_1), // Fed by dedicated Watchdog loop 1 from Synchronizer
        .write_enb        (wire_write_enb[1]), // Activated when wire_write_enb decoded output array = 3'b010
        .read_enb         (read_enb_1),
        .lfd_state        (wire_lfd_state),
        .d_in             (wire_d_out),
        .d_out            (data_out_1),        // Drives the physical external data output channel 1 pins
        .vld_out          (),                  // Left un-connected because Synchronizer Block 1 handles vld_out logic paths
        .full             (wire_full_1),
        .empty            (wire_empty_1)
    );

    // 6. Instantiation of Storage Queue Channel 2 (FIFO 2)
    router_fifo #(
        .DEPTH            (16),
        .DATA_WIDTH       (8),
        .ADDR_WIDTH       (4)
    ) FIFO_CHANNEL_2 (
        .clk              (clk),
        .resetn           (resetn),
        .soft_reset       (wire_soft_reset_2), // Fed by dedicated Watchdog loop 2 from Synchronizer
        .write_enb        (wire_write_enb[2]), // Activated when wire_write_enb decoded output array = 3'b100
        .read_enb         (read_enb_2),
        .lfd_state        (wire_lfd_state),
        .d_in             (wire_d_out),
        .d_out            (data_out_2),        // Drives the physical external data output channel 2 pins
        .vld_out          (),                  // Left un-connected because Synchronizer Block 1 handles vld_out logic paths
        .full             (wire_full_2),
        .empty            (wire_empty_2)
    );

endmodule
